package controller;

public enum GameStrings {

    // === VALUES FOR ENUM ===
    DIFFICULTY_QUESTION,
    CONTINUE_QUESTION,
    GUESS_QUESTION,

    WIN_DECLARATION,
    TRY_AGAIN_DECLARATION,
    POSITIVE_RESULT_DECLARATION,
    NEGATIVE_RESULT_DECLARATION,
    HIGHER_GUESS_DECLARATION,
    LOWER_GUESS_DECLARATION,
    GAME_OVER_DECLARATION,

    SYSTEM_INVALID_INPUT,

    BASIC_STRING_NEWLINE

}
